# Generated by Django 2.1.11 on 2021-01-25 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sign',
            fields=[
                ('sign_id', models.AutoField(primary_key=True, serialize=False)),
                ('sign_name', models.CharField(max_length=100)),
                ('sign_type', models.CharField(default='无', max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('update_user', models.CharField(default='', max_length=30)),
            ],
            options={
                'verbose_name': '签名管理',
                'verbose_name_plural': '签名管理',
            },
        ),
    ]
