# Generated by Django 2.1.11 on 2021-01-25 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Plan', '0002_plan_project'),
        ('djcelery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('report_name', models.CharField(max_length=255)),
                ('report_path', models.CharField(default='', max_length=255, null=True)),
                ('pic_name', models.CharField(default='', max_length=255)),
                ('totalTime', models.CharField(default='', max_length=50)),
                ('startTime', models.CharField(default='', max_length=50)),
                ('content', models.TextField()),
                ('case_num', models.IntegerField(null=True)),
                ('skip_num', models.IntegerField(null=True)),
                ('pass_num', models.IntegerField(null=True)),
                ('fail_num', models.IntegerField(null=True)),
                ('error_num', models.IntegerField(null=True)),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('update_user', models.CharField(default='', max_length=30)),
                ('make', models.IntegerField(null=True)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Plan.Plan')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='djcelery.PeriodicTask')),
            ],
            options={
                'verbose_name': '测试报告',
                'verbose_name_plural': '测试报告',
            },
        ),
    ]
