# Generated by Django 2.1.11 on 2021-01-25 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('env_id', models.AutoField(primary_key=True, serialize=False)),
                ('env_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=100)),
                ('import_url', models.CharField(default='', max_length=100)),
                ('is_swagger', models.IntegerField(default=0)),
                ('set_headers', models.TextField(default='')),
                ('private_key', models.CharField(max_length=100)),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('update_user', models.CharField(default='', max_length=30)),
            ],
            options={
                'verbose_name': '测试环境',
                'verbose_name_plural': '测试环境',
            },
        ),
    ]
