# Generated by Django 2.1.11 on 2021-01-25 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('if_id', models.AutoField(primary_key=True, serialize=False)),
                ('if_name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('method', models.CharField(max_length=10)),
                ('data_type', models.CharField(max_length=10)),
                ('is_sign', models.IntegerField()),
                ('is_header', models.IntegerField(default=0)),
                ('set_mock', models.TextField(default='')),
                ('skip', models.TextField(default='')),
                ('description', models.CharField(max_length=200)),
                ('request_header_param', models.TextField()),
                ('request_body_param', models.TextField()),
                ('response_header_param', models.TextField()),
                ('response_body_param', models.TextField()),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('update_user', models.CharField(default='', max_length=30)),
            ],
            options={
                'verbose_name': '接口管理',
                'verbose_name_plural': '接口管理',
            },
        ),
    ]
