# Generated by Django 2.1.11 on 2021-01-25 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Environment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('plan_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('report_name', models.CharField(default='', max_length=255)),
                ('make', models.IntegerField(null=True)),
                ('is_locust', models.IntegerField(default=0)),
                ('is_task', models.IntegerField(default=0)),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('update_user', models.CharField(default='', max_length=30)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Environment.Environment')),
            ],
            options={
                'verbose_name': '测试计划',
                'verbose_name_plural': '测试计划',
            },
        ),
    ]
