# Generated by Django 3.1.3 on 2021-01-26 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Module', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': '产品管理', 'verbose_name_plural': '产品管理'},
        ),
    ]
