# Generated by Django 3.1.3 on 2021-01-27 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Module', '0002_auto_20210126_2238'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModularTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('Icon', models.CharField(max_length=255)),
                ('model_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': '模块名称',
                'verbose_name_plural': '模块名称',
            },
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
